title: "Anil Regmi"
email: "your.email@example.com"
description: "Geologist | Explorer | Researcher"
baseurl: "" # leave this empty
url: "https://anilregmi9.com.np"
linkedin_username: "your-linkedin"
github_username: "anilregmi9"
# Optional:
twitter_username: "your-twitter"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Custom variables
name: "Anil Regmi"
